version: 2.1
jobs:
  build:
    working_directory: ~/jestTesimg
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "npm install"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Cache Clean Dependencies
          command: npm cache clean --force
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Unit(Jest) tests
          command: npm run test
      - run:
          name: Run Automation(Detox) tests
          command: npm run cleanDetoxEmuAndroid